
WITH DATA_TKTIETKIEM AS
	(
	SELECT * FROM
		(SELECT * FROM
			-- DK
			(
				SELECT 
					Cust_ID					AS [DAUKY_MKH]
					,Saving_account_ID			AS [DAUKY_MATK]
					,Value					AS [DAUKY_TONGTIENTK]
					,Sav_Date				AS [DAUKY_NGAYBATDAU]
					,Sav_end_date				AS [DAUKY_NGAYTATTOAN]
				FROM SAVING_ACCOUNT
				WHERE Sav_Date <= '2023-12-31' AND (Sav_end_date > '2023-12-31' OR withdraw_day > '2023-12-31')
			-- MM
			FULL OUTER JOIN
			(
				SELECT 
					Cust_ID					AS [MOMOI_MKH]
					,Saving_account_ID			AS [MOMOI_MATK]
					,Value					AS [MOMOI_TONGTIENTK]
					,Sav_Date				AS [MOMOI_NGAYBATDAU]
					,Sav_end_date				AS [MOMOI_NGAYTATTOAN]
				FROM SAVING_ACCOUNT
				WHERE Sav_Date BETWEEN '2024-01-01' AND '2024-06-30'  		
			) MOMOI
			ON DAUKY.DAUKY_MATK = MOMOI.MOMOI_MATK) AS X
			
			-- TT
			LEFT JOIN
			(
				SELECT 
					Cust_ID					AS [TATTOAN_MKH]
					,Saving_account_ID			AS [TATTOAN_MATK]
					,Value					AS [TATTOAN_TONGTIENTK]
					,Sav_Date				AS [TATTOAN_NGAYBATDAU]
					,Sav_end_date				AS [TATTOAN_NGAYTATTOAN]
				FROM SAVING_ACCOUNT
				WHERE Sav_end_date BETWEEN '2024-01-01' AND '2024-06-30'
					OR withdraw_day BETWEEN '2024-01-01' AND '2024-06-30'	
			) TATTOAN
			ON ISNULL(X.DAUKY_MATK,'') + ISNULL(X.MOMOI_MATK,'') = TATTOAN.TATTOAN_MATK
			-- CK
			LEFT JOIN
			(
				SELECT
					Cust_ID					AS [CUOIKY_MKH]
					,Saving_account_ID			AS [CUOIKY_MATK]
					,Value					AS [CUOIKY_TONGTIENTK]
					,Sav_Date				AS [CUOIKY_NGAYBATDAU]
					,Sav_end_date				AS [CUOIKY_NGAYTATTOAN]
				FROM SAVING_ACCOUNT
				WHERE Sav_date <= '2024-06-30' AND Sav_end_date > '2024-06-30'			
			) CUOIKY
			ON ISNULL(X.DAUKY_MATK,'') + ISNULL(X.MOMOI_MATK,'') = CUOIKY.CUOIKY_MATK
)
-- NAME THE FINAL DATA TABLE
SELECT * 
INTO DATA_TKTIETKIEM_FINAL
FROM DATA_TKTIETKIEM

SELECT * FROM DATA_TKTIETKIEM_FINAL
----------------------------------------------------
**Report on Capital Mobilization in the First 6 Months of the Year**
----------------------------------------------------

-- CREATE REPORT BY TEMPLATE
DROP TABLE [Report on Capital Mobilization in the First 6 Months of the Year]
CREATE TABLE [Report on Capital Mobilization in the First 6 Months of the Year]
(
   STT						Int
  ,[NOI DUNG]					Nvarchar(100)
  ,[TAI THOI DIEM 31/12/2023]			bigint
  ,[MO MOI_Q1_24]				bigint
  ,[TAT TOAN_Q1_24]				bigint
  ,[MO MOI_Q2_24]				bigint
  ,[TAT TOAN_Q2_24]				bigint
  ,[TAI THOI DIEM 30/06/2024]			bigint
);

INSERT INTO [Report on Capital Mobilization in the First 6 Months of the Year]
(
	 STT
	,[NOI DUNG]
	,[TAI THOI DIEM 31/12/2023]
	,[MO MOI_Q1_24]
	,[TAT TOAN_Q1_24]
	,[MO MOI_Q2_24]
	,[TAT TOAN_Q2_24]
	,[TAI THOI DIEM 30/06/2024]
)
VALUES
 (1,N'Số khoản tiết kiệm',NULL,NULL,NULL,NULL,NULL,NULL)
,(2,N'Số lượng khách hàng',NULL,NULL,NULL,NULL,NULL,NULL)
,(3,N'Tổng tiền gửi tiết kiệm',NULL,NULL,NULL,NULL,NULL,NULL)

-- I. UPDATE INFORMATION RELATED TO SAVINGS ACCOUNT NUMBER (SKTK)
-- DK:
UPDATE [Report on Capital Mobilization in the First 6 Months of the Year]
SET [TAI THOI DIEM 31/12/2023] = (
CASE WHEN [NOI DUNG] = N'Số khoản tiết kiệm'		THEN (SELECT COUNT(DISTINCT(DAUKY_MATK)) FROM DATA_TKTIETKIEM_FINAL)
	 WHEN [NOI DUNG] = N'Số lượng khách hàng'	THEN (SELECT COUNT(DISTINCT(DAUKY_MKH))  FROM DATA_TKTIETKIEM_FINAL)
	 WHEN [NOI DUNG] = N'Tổng tiền gửi tiết kiệm'	THEN (SELECT SUM(DAUKY_TONGTIENTK)	 FROM DATA_TKTIETKIEM_FINAL) 
	 END
)	
-- MM
UPDATE [Report on Capital Mobilization in the First 6 Months of the Year]
SET [MO MOI_Q1_24] = (
CASE WHEN [NOI DUNG] = N'Số khoản tiết kiệm'		THEN (SELECT COUNT(DISTINCT(MOMOI_MATK)) FROM DATA_TKTIETKIEM_FINAL WHERE DAUKY_MATK IS NULL AND DATEPART(QUARTER,MOMOI_NGAYBATDAU) = 1)
	 WHEN [NOI DUNG] = N'Số lượng khách hàng'		THEN 
		(SELECT 
			COUNT(MOMOI_MKH) AS [MOMOI_SOLUONGKH]
		FROM
			(SELECT
				DISTINCT(MOMOI_MKH)
			FROM DATA_TKTIETKIEM_FINAL
			WHERE DATEPART(QUARTER,MOMOI_NGAYBATDAU) = 1) MM
			LEFT JOIN
			(SELECT
				DISTINCT(DAUKY_MKH)
			FROM DATA_TKTIETKIEM_FINAL) DK
			ON MM.MOMOI_MKH = DK.DAUKY_MKH
			WHERE DK.DAUKY_MKH IS NULL)
	 WHEN [NOI DUNG] = N'Tổng tiền gửi tiết kiệm'	THEN (SELECT SUM(MOMOI_TONGTIENTK) FROM DATA_TKTIETKIEM_FINAL WHERE DAUKY_MATK IS NULL AND DATEPART(QUARTER,MOMOI_NGAYBATDAU) = 1) 
	 END
)	
UPDATE [Report on Capital Mobilization in the First 6 Months of the Year]
SET [MO MOI_Q2_24] = (
CASE WHEN [NỘI DUNG] = N'Số khoản tiết kiệm'		THEN (SELECT COUNT(DISTINCT(MOMOI_MATK)) FROM DATA_TKTIETKIEM_FINAL WHERE DAUKY_MATK IS NULL AND DATEPART(QUARTER,MOMOI_NGAYBATDAU) = 2)
	 WHEN [NỘI DUNG] = N'Số lượng khách hàng'		THEN 
		(SELECT 
    COUNT(MOMOI_MKHQ2) AS [MOMOI_SOLUONGKH]
FROM
    (SELECT DISTINCT(MOMOI_MKH) AS [MOMOI_MKHQ2]
     FROM DATA_TKTIETKIEM_FINAL
     WHERE DATEPART(QUARTER, MOMOI_NGAYBATDAU) = 2) MM
LEFT JOIN
    (SELECT DISTINCT(DAUKY_MKH)
     FROM DATA_TKTIETKIEM_FINAL) DK
ON MM.MOMOI_MKHQ2 = DK.DAUKY_MKH
LEFT JOIN
    (SELECT DISTINCT(MOMOI_MKH) AS [MOMOI_MKHQ1]
     FROM DATA_TKTIETKIEM_FINAL
     WHERE DATEPART(QUARTER, MOMOI_NGAYBATDAU) = 1) MM_Q1
ON MM.MOMOI_MKHQ2 = MM_Q1.MOMOI_MKHQ1
WHERE DK.DAUKY_MKH IS NULL
  AND MM_Q1.MOMOI_MKHQ1 IS NULL
)
	 WHEN [NỘI DUNG] = N'Tổng tiền gửi tiết kiệm'	THEN (SELECT SUM(MOMOI_TONGTIENTK) FROM DATA_TKTIETKIEM_FINAL WHERE DAUKY_MATK IS NULL AND DATEPART(QUARTER,MOMOI_NGAYBATDAU) = 2) 
	 END
)	
-- TT:
UPDATE [Report on Capital Mobilization in the First 6 Months of the Year]
SET [TAT TOAN_Q1_24] = (
CASE WHEN [NỘI DUNG] = N'Số khoản tiết kiệm'		THEN (SELECT COUNT(DISTINCT(TATTOAN_MATK)) FROM DATA_TKTIETKIEM_FINAL WHERE CUOIKY_MATK IS NULL AND DATEPART(QUARTER,TATTOAN_NGAYTATTOAN) = 1 )
	 WHEN [NOI DUNG] = N'Số lượng khách hàng'		THEN 
		(SELECT 
			COUNT(TATTOAN_MKH) AS [TATTOAN_SOLUONGKH]
		FROM
			(SELECT
				DISTINCT(TATTOAN_MKH)
			FROM DATA_TKTIETKIEM_FINAL
			WHERE DATEPART(QUARTER,TATTOAN_NGAYTATTOAN) = 1) TT
			LEFT JOIN
			(SELECT
				DISTINCT(CUOIKY_MKH)
			FROM DATA_TKTIETKIEM_FINAL) CK
			ON TT.TATTOAN_MKH = CK.CUOIKY_MKH
			WHERE CK.CUOIKY_MKH IS NULL)
	WHEN [NOI DUNG] = N'Tổng tiền gửi tiết kiệm'	THEN (SELECT SUM(TATTOAN_TONGTIENTK) FROM DATA_TKTIETKIEM_FINAL WHERE CUOIKY_MATK IS NULL AND DATEPART(QUARTER,TATTOAN_NGAYTATTOAN) = 1) 
	END
)
-- Q2/2024
UPDATE [Report on Capital Mobilization in the First 6 Months of the Year]
SET [TAT TOAN_Q2_24] = (
CASE WHEN [NỘI DUNG] = N'Số khoản tiết kiệm'		THEN (SELECT COUNT(DISTINCT(TATTOAN_MATK)) FROM DATA_TKTIETKIEM_FINAL WHERE CUOIKY_MATK IS NULL AND DATEPART(QUARTER,TATTOAN_NGAYTATTOAN) = 2)
	 WHEN [NOI DUNG] = N'Số lượng khách hàng'		THEN 
		(SELECT 
			COUNT(TATTOAN_MKH) AS [TATTOAN_SOLUONGKH]
		FROM
			(SELECT
				DISTINCT(TATTOAN_MKH)
			FROM DATA_TKTIETKIEM_FINAL
			WHERE DATEPART(QUARTER,TATTOAN_NGAYTATTOAN) = 2) TT
			LEFT JOIN
			(SELECT
				DISTINCT(CUOIKY_MKH)
			FROM DATA_TKTIETKIEM_FINAL) CK
			ON TT.TATTOAN_MKH = CK.CUOIKY_MKH
			WHERE CK.CUOIKY_MKH IS NULL)
	WHEN [NOI DUNG] = N'Tổng tiền gửi tiết kiệm'	THEN (SELECT SUM(TATTOAN_TONGTIENTK) FROM DATA_TKTIETKIEM_FINAL WHERE CUOIKY_MATK IS NULL AND DATEPART(QUARTER,TATTOAN_NGAYTATTOAN) = 2) 
	END
)	
-- CK:
UPDATE [Report on Capital Mobilization in the First 6 Months of the Year]
SET [TAI THOI DIEM 30/06/2024] = (
CASE WHEN [NOI DUNG] = N'Số khoản tiết kiệm'		THEN (SELECT COUNT(DISTINCT(CUOIKY_MATK)) FROM DATA_TKTIETKIEM_FINAL)
	 WHEN [NOI DUNG] = N'Số lượng khách hàng'		THEN (SELECT COUNT(DISTINCT(CUOIKY_MKH))  FROM DATA_TKTIETKIEM_FINAL)
	 WHEN [NOI DUNG] = N'Tổng tiền gửi tiết kiệm'	THEN (SELECT SUM(CUOIKY_TONGTIENTK)		  FROM DATA_TKTIETKIEM_FINAL) 
	 END
)

-- RESULT:
SELECT * FROM [Report on Capital Mobilization in the First 6 Months of the Year]
